# Generated by Django 4.1.3 on 2022-12-07 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dealingwithjson', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jsontosql',
            name='high',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='jsontosql',
            name='volume',
            field=models.CharField(max_length=50),
        ),
    ]
